trigger: none
pr: none

jobs:
    - job: 'macOS'
      pool:
          vmImage: 'macOS-10.14'
      strategy:
          matrix:
              Python27:
                  python.version: '2.7'
                  PYTHON_DOWNLOAD_URL: "https://www.python.org/ftp/python/2.7.16/python-2.7.16-macosx10.6.pkg"
                  PYTHON_BIN_PATH: /Library/Frameworks/Python.framework/Versions/2.7/bin/python
              Python3:
                  python.version: '3.4'
                  PYTHON_DOWNLOAD_URL: "https://www.python.org/ftp/python/3.7.3/python-3.7.3-macosx10.6.pkg"
                  PYTHON_BIN_PATH: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
      steps:
          - script: |
              set -e
              set -x

              curl "$PYTHON_DOWNLOAD_URL" -o python.pkg
              sudo installer -pkg python.pkg -target /
            displayName: Download and install Python

          - script: $PYTHON_BIN_PATH -m pip install -U virtualenv
            displayName: Install virtualenv
          - script: $PYTHON_BIN_PATH -m virtualenv .venv
            displayName: Create virtualenv
          - script: .venv/bin/pip install -U wheel
            displayName: Update wheel to the latest version
          - script: .venv/bin/pip install cffi six
            displayName: Install our Python dependencies

          - script: |
              set -e
              set -x

              REGEX="3\.([0-9])*"
              if [[ "$PYTHON_VERSION" =~ $REGEX ]]; then
                  PY_LIMITED_API="--build-option --py-limited-api=cp3${BASH_REMATCH[1]}"
              fi

              .venv/bin/pip wheel pynacl --no-use-pep517 --wheel-dir=wheelhouse --no-binary pynacl --no-deps $PY_LIMITED_API
            displayName: Build the wheel
          - script: .venv/bin/pip install --no-index -f wheelhouse pynacl
            displayName: Test installing the wheel
          - script: |
              .venv/bin/python -c "import nacl.signing; key = nacl.signing.SigningKey.generate();signature = key.sign(b'test'); key.verify_key.verify(signature)"
            displayName: Test the installed wheel
          - task: PublishBuildArtifacts@1
            inputs:
                pathToPublish: wheelhouse/
                artifactName: pynacl-macos-python$(python.version)

    - job: 'manylinux1'
      pool:
          vmImage: 'ubuntu-16.04'
      container: 'pyca/cryptography-manylinux1:x86_64'
      strategy:
          matrix:
              Python27m:
                  PYTHON_VERSION: 'cp27-cp27m'
              Python27mu:
                  PYTHON_VERSION: 'cp27-cp27mu'
              Python3m:
                  PYTHON_VERSION: 'cp34-cp34m'
      steps:
          - script: /opt/python/$PYTHON_VERSION/bin/python -m virtualenv .venv
            displayName: Create virtualenv
          - script: .venv/bin/pip install cffi six
            displayName: Install our Python dependencies
          - script: |
              set -e
              set -x

              REGEX="cp3([0-9])*"
              if [[ "$PYTHON_VERSION" =~ $REGEX ]]; then
                  PY_LIMITED_API="--build-option --py-limited-api=cp3${BASH_REMATCH[1]}"
              fi
              .venv/bin/pip wheel pynacl --no-use-pep517 --no-binary pynacl --no-deps --wheel-dir=tmpwheelhouse $PY_LIMITED_API
            displayName: Build the wheel
          - script: auditwheel repair tmpwheelhouse/PyNaCl*.whl -w wheelhouse/
            displayName: Run auditwheel
          - script: .venv/bin/pip install pynacl --no-index -f wheelhouse/
            displayName: Test installing the wheel
          - script: |
              .venv/bin/python -c "import nacl.signing; key = nacl.signing.SigningKey.generate();signature = key.sign(b'test'); key.verify_key.verify(signature)"
            displayName: Test the installed wheel
          - task: PublishBuildArtifacts@1
            inputs:
                pathToPublish: wheelhouse/
                artifactName: pynacl-manylinux1-$(PYTHON_VERSION)

    - job: 'windows'
      pool:
          vmImage: 'windows-2019'
      container: $[variables.containerImage]
      strategy:
          matrix:
              Python27-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py27-x86'
                  SODIUM_LIB_PATH: 'C:/libsodium/Win32/Release/v100/static'
                  PYTHON_VERSION: '27'
                  WINDOWS_ARCH: 'x86'
              Python27-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py27-x86_64'
                  SODIUM_LIB_PATH: 'C:/libsodium/x64/Release/v100/static'
                  PYTHON_VERSION: '27'
                  WINDOWS_ARCH: 'x86_64'
              Python34-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py34-x86'
                  SODIUM_LIB_PATH: 'C:/libsodium/Win32/Release/v100/static'
                  PYTHON_VERSION: '34'
                  WINDOWS_ARCH: 'x86'
              Python34-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py34-x86_64'
                  SODIUM_LIB_PATH: 'C:/libsodium/x64/Release/v100/static'
                  PYTHON_VERSION: '34'
                  WINDOWS_ARCH: 'x86_64'
              Python35-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py35-x86'
                  SODIUM_LIB_PATH: 'C:/libsodium/Win32/Release/v140/static'
                  PYTHON_VERSION: '35'
                  WINDOWS_ARCH: 'x86'
              Python35-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py35-x86_64'
                  SODIUM_LIB_PATH: 'C:/libsodium/x64/Release/v140/static'
                  PYTHON_VERSION: '35'
                  WINDOWS_ARCH: 'x86_64'
              Python36-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py3-x86'
                  SODIUM_LIB_PATH: 'C:/libsodium/Win32/Release/v140/static'
                  PYTHON_VERSION: '36'
                  WINDOWS_ARCH: 'x86'
              Python36-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py3-x86_64'
                  SODIUM_LIB_PATH: 'C:/libsodium/x64/Release/v140/static'
                  PYTHON_VERSION: '36'
                  WINDOWS_ARCH: 'x86_64'
              Python37-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py3-x86'
                  SODIUM_LIB_PATH: 'C:/libsodium/Win32/Release/v140/static'
                  PYTHON_VERSION: '37'
                  WINDOWS_ARCH: 'x86'
              Python37-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py3-x86_64'
                  SODIUM_LIB_PATH: 'C:/libsodium/x64/Release/v140/static'
                  PYTHON_VERSION: '37'
                  WINDOWS_ARCH: 'x86_64'
      steps:
          - powershell: |
              $url = "https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-msvc.zip"
              $sha256hash = "C1D48D85C9361E350931FFE5067559CD7405A697C655D26955FB568D1084A5F4"
              Write-Host ('Downloading {0} ...' -f $url)
              [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
              # See https://github.com/PowerShell/PowerShell/issues/2138
              $ProgressPreference = 'SilentlyContinue'
              Invoke-WebRequest -Uri $url -OutFile 'libsodium.zip'
              if ((Get-FileHash libsodium.zip -Algorithm "SHA256").Hash -ne $sha256hash) {
                exit 1
              }
              Expand-Archive libsodium.zip -DestinationPath c:\
            displayName: 'Download libsodium libraries'
          - powershell: |
              Copy-Item ".azure-pipelines/windows/stdint.h" -Destination "C:/libsodium/include/stdint.h"
            displayName: 'Copy stdint.h to include dir (distant weeping)'
          - script: '"C:/Python%PYTHON_VERSION%/Scripts/pip" install wheel cffi six'
            displayName: Install wheel and our Python dependencies
          - script: |
              set PYNACL_SODIUM_LIBRARY_NAME=sodium
              set PYNACL_SODIUM_STATIC=1
              set SODIUM_INSTALL=system
              set INCLUDE=C:/libsodium/include;%INCLUDE%
              set LIB=%SODIUM_LIB_PATH%;%LIB%
              C:/Python%PYTHON_VERSION%/Scripts/pip wheel pynacl --no-use-pep517 --wheel-dir=wheelhouse --no-binary pynacl
            displayName: Build the wheel
          - script: '"C:/Python%PYTHON_VERSION%/Scripts/pip" install -f wheelhouse pynacl --no-index'
            displayName: Test installing the wheel
          - script: |
              "C:/Python%PYTHON_VERSION%/python" -c "import nacl.signing; key = nacl.signing.SigningKey.generate();signature = key.sign(b'test'); key.verify_key.verify(signature)"
            displayName: Test the installed wheel
          - script: mkdir pynacl-wheelhouse
            displayName: Create a directory for placing the final wheel in
          - script: move wheelhouse\pynacl*.whl pynacl-wheelhouse\
            displayName: Move the pynacl wheel into the final wheel house
          - task: PublishBuildArtifacts@1
            inputs:
                pathToPublish: pynacl-wheelhouse/
                artifactName: pynacl-windows-$(WINDOWS_ARCH)-python$(PYTHON_VERSION)
